In [ ]:
from google.colab import drive
drive.mount("content/drive/Chatbot/health.txt")

### Importing necessary modules

In [ ]:
# Natural Language Toolkit
import nltk

In [ ]:
# library for NLP
import spacy

### Text Pre-processing & Tokenization

In [ ]:
# regular expression
import re

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    # Lowercasing
    text = text.lower()

    # Remove special characters, numbers, and punctuation
    text = re.sub(r'[^a-z\s]', '', text)

    return text

def tokenize_and_lemmatize(text):
    # Tokenization and lemmatization using spaCy
    doc = nlp(text)
    lemmatized_tokens = [token.lemma_ for token in doc if not token.is_stop]

    return lemmatized_tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


### Loading text document

In [ ]:
with open("health.txt", 'r', encoding='utf-8') as file:
    dataset = file.read()

print(dataset)

Cardiovascular health is crucial for overall well-being. Regular exercise, a balanced diet, and avoiding smoking are key factors in maintaining a healthy heart. It's essential to monitor cholesterol levels and blood pressure regularly.

Diabetes is a chronic condition that requires careful management. Individuals with diabetes should focus on controlling their blood sugar levels through a combination of diet, exercise, and medication as prescribed by their healthcare provider.

Mental health is as important as physical health. Stress management techniques, such as meditation and deep breathing exercises, can contribute to overall well-being. If experiencing persistent mental health issues, seeking professional help is advisable.

Adequate sleep is crucial for cognitive function and overall health. Establishing a consistent sleep routine, creating a comfortable sleep environment, and avoiding stimulants before bedtime can contribute to better sleep quality.

The Mediterranean diet, rich

In [ ]:
# Split the dataset into paragraphs
paragraphs = dataset.split('\n')

print(len(paragraphs))

20


In [ ]:
# Clean and preprocess each paragraph
cleaned_paragraphs = [clean_text(paragraph) for paragraph in paragraphs]
preprocessed_paragraphs = [tokenize_and_lemmatize(paragraph) for paragraph in cleaned_paragraphs]

# removing newline characters
for i in preprocessed_paragraphs:
    if i==[]:
        preprocessed_paragraphs.remove(i)

# Print the cleaned and preprocessed paragraphs
for i, paragraph in enumerate(preprocessed_paragraphs, 1):
    print(f"Paragraph {i}:\n{paragraph}\n")

Paragraph 1:
['cardiovascular', 'health', 'crucial', 'overall', 'wellbee', 'regular', 'exercise', 'balanced', 'diet', 'avoid', 'smoking', 'key', 'factor', 'maintain', 'healthy', 'heart', 'essential', 'monitor', 'cholesterol', 'level', 'blood', 'pressure', 'regularly']

Paragraph 2:
['diabetes', 'chronic', 'condition', 'require', 'careful', 'management', 'individual', 'diabete', 'focus', 'control', 'blood', 'sugar', 'level', 'combination', 'diet', 'exercise', 'medication', 'prescribe', 'healthcare', 'provider']

Paragraph 3:
['mental', 'health', 'important', 'physical', 'health', 'stress', 'management', 'technique', 'meditation', 'deep', 'breathing', 'exercise', 'contribute', 'overall', 'wellbeing', 'experience', 'persistent', 'mental', 'health', 'issue', 'seek', 'professional', 'help', 'advisable']

Paragraph 4:
['adequate', 'sleep', 'crucial', 'cognitive', 'function', 'overall', 'health', 'establish', 'consistent', 'sleep', 'routine', 'create', 'comfortable', 'sleep', 'environment', '

In [ ]:
len(preprocessed_paragraphs)

10

## Embedding Techniques

### Word Embeddings:

In [ ]:
words = []
for i in preprocessed_paragraphs:
    for j in i:
        words.append(j)

print(len(words))

213


In [ ]:
unique_words = []
for i in words:
    if i not in unique_words:
        unique_words.append(i)

print(len(unique_words))

139


In [ ]:
print(unique_words)

['cardiovascular', 'health', 'crucial', 'overall', 'wellbee', 'regular', 'exercise', 'balanced', 'diet', 'avoid', 'smoking', 'key', 'factor', 'maintain', 'healthy', 'heart', 'essential', 'monitor', 'cholesterol', 'level', 'blood', 'pressure', 'regularly', 'diabetes', 'chronic', 'condition', 'require', 'careful', 'management', 'individual', 'diabete', 'focus', 'control', 'sugar', 'combination', 'medication', 'prescribe', 'healthcare', 'provider', 'mental', 'important', 'physical', 'stress', 'technique', 'meditation', 'deep', 'breathing', 'contribute', 'wellbeing', 'experience', 'persistent', 'issue', 'seek', 'professional', 'help', 'advisable', 'adequate', 'sleep', 'cognitive', 'function', 'establish', 'consistent', 'routine', 'create', 'comfortable', 'environment', 'stimulant', 'bedtime', 'well', 'quality', 'mediterranean', 'rich', 'fruit', 'vegetable', 'grain', 'olive', 'oil', 'associate', 'numerous', 'benefit', 'know', 'promote', 'weight', 'reduce', 'risk', 'disease', 'quit', 'challe

### One-Hot Encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Convert paragraphs to a DataFrame
df = pd.DataFrame({'word': unique_words})

# Use OneHotEncoder
encoder = OneHotEncoder(sparse=False)
one_hot_encoded = encoder.fit_transform(df[['word']])

print("One-Hot Encoded:")
print(one_hot_encoded)

One-Hot Encoded:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
print(one_hot_encoded[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
one_hot_encoded[0].shape

(139,)

### Bag of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Convert paragraphs to a list of strings
paragraphs_str = [' '.join(paragraph) for paragraph in preprocessed_paragraphs]

# Create a CountVectorizer
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(paragraphs_str)

print("Bag of Words Matrix:")
print(bow_matrix.toarray())

Bag of Words Matrix:
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(bow_matrix.toarray()[2])

[0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 3 0 0 0 1 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 0 2 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0]


### TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Convert paragraphs to a list of strings
paragraphs_str = [' '.join(paragraph) for paragraph in preprocessed_paragraphs]

# Create a TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(paragraphs_str)

print("TF-IDF Matrix:")
print(tfidf_matrix.toarray())

TF-IDF Matrix:
[[0.         0.         0.         ... 0.2504722  0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.21376929 ... 0.         0.21376929 0.        ]
 ...
 [0.         0.19761223 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
print(tfidf_matrix.toarray()[0])

[0.         0.         0.         0.         0.         0.21292425
 0.21292425 0.         0.         0.21292425 0.         0.
 0.21292425 0.         0.         0.         0.         0.
 0.2504722  0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.18628356
 0.         0.         0.         0.         0.         0.16561944
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.18628356 0.
 0.16561944 0.         0.2504722  0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.11118767 0.         0.18628356 0.21292425 0.         0.
 0.         0.         0.         0.         0.         0.
 0.21292425 0.         0.         0.21292425 0.16561944 0.
 0.         0.         0.         0.         0.2504722  0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.16561944 0.         0.         0.
 0.         0.2504722  0.       

### Word2Vec

In [ ]:
from gensim.models import Word2Vec
import gensim
import warnings
warnings.filterwarnings(action='ignore')

para = preprocessed_paragraphs

In [ ]:
# Create CBOW model (continuous bag of words)
model1 = gensim.models.Word2Vec(para, min_count=1,
                                vector_size=100, window=5)

# Print results
print("Cosine similarity between 'heart' " +
      "and 'cardiovascular' - CBOW : ",
      model1.wv.similarity('heart', 'cardiovascular'))

print("Cosine similarity between 'heart' " +
      "and 'exercise' - CBOW : ",
      model1.wv.similarity('heart', 'exercise'))

Cosine similarity between 'heart' and 'cardiovascular' - CBOW :  0.023253532
Cosine similarity between 'heart' and 'exercise' - CBOW :  0.03419761


In [ ]:
# Create Skip Gram model
model2 = gensim.models.Word2Vec(para, min_count=1, vector_size=100,
                                window=5, sg=1)

# Print results
print("Cosine similarity between 'heart' " +
      "and 'cardiovascular' - Skip Gram : ",
      model2.wv.similarity('heart', 'cardiovascular'))

print("Cosine similarity between 'heart' " +
      "and 'exercise' - Skip Gram : ",
      model2.wv.similarity('heart', 'exercise'))

Cosine similarity between 'heart' and 'cardiovascular' - Skip Gram :  0.031060148
Cosine similarity between 'heart' and 'exercise' - Skip Gram :  0.04141001


### FastText

In [ ]:
!pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 731.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Using cached pybind11-2.11.1-py3-none-any.whl (227 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp310-cp310-linux_x86_64.whl size=4199774 sha256=41b4cb9dae23ee9df58acb7976b0f0c2c9f46882fde1fdbea63b10127ce25794
  Stored in directory: /root/.cache/pip/wheels/a5/13/75/f811c84a8ab36eedbaef977a6a58a98990e8e0f1967f98f394
Successfully built fasttext


In [ ]:
# joining the words by space in each element
joint = []
for i in para:
  joint.append(' '.join(i))

In [ ]:
# Save preprocessed data to a text file
altered = "altered_health.txt"
with open(altered, "w") as a_file:
    a_file.write('\n'.join(joint))

In [ ]:
# Train FastText model
import fasttext
model = fasttext.train_unsupervised(altered, model='skipgram', dim=100, epoch=10)

In [ ]:
# Get the vector for a specific word
word_vector = model.get_word_vector("health")

print("Vector for 'health':", word_vector)

Vector for 'health': [-4.05785482e-04  5.00571332e-04 -2.00262366e-04 -2.55653285e-04
  3.63889674e-04  1.91550032e-04  2.28520585e-04  3.32912532e-05
  4.80392569e-04  4.67677251e-04 -9.36014258e-05  6.32695956e-05
  4.20547032e-04  4.18728945e-04 -3.17113358e-04 -2.02521318e-04
  7.14762718e-05  4.04394028e-04 -6.62395760e-05 -4.45568643e-04
 -1.48450985e-04  5.21324342e-04  3.52722069e-04 -2.20005677e-04
  1.64534242e-04 -4.38835763e-04 -6.74953553e-05 -2.21836090e-04
 -1.29997541e-04  4.13814967e-04 -4.38320363e-04 -1.86014324e-04
 -3.91636218e-04 -4.41969285e-04 -5.96355530e-04 -6.82532263e-05
  7.34719433e-05 -3.95966345e-04 -1.23488076e-04 -3.97349475e-04
  3.66439665e-04  5.47844509e-04  1.06830055e-04  1.42785924e-04
 -1.23222460e-04  1.31390319e-04 -1.16527204e-04 -2.96815968e-04
 -4.94392239e-04  1.96446068e-04 -3.90156667e-04  4.49477491e-04
 -4.52328182e-04  3.28063936e-04 -1.79545561e-04 -2.37955683e-04
 -7.60800904e-05  1.22528334e-04  3.50169314e-04  1.38448755e-04
 -3.

In [ ]:
# Find the most similar words to a given word
similar_words = model.get_nearest_neighbors("heart", k=10)
print("\nMost similar words to 'heart':")
for word, score in similar_words:
    print(f"{word}: {score}")


Most similar words to 'heart':
0.03030896745622158: health
0.012669890187680721: </s>
-0.08562008291482925: management


### BERT

In [ ]:
from transformers import BertTokenizer, BertModel
import torch

In [ ]:
# Load pre-trained BERT model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertModel.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
# Define a function to obtain BERT embeddings for a word
def get_bert_embedding(word):
    inputs = tokenizer(word, return_tensors="pt")
    outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.mean(dim=1)  # Taking the mean of hidden states as the word embedding
    return embeddings

In [ ]:
# Example usage
word = para[0][0]
bert_embedding = get_bert_embedding(word)

print("BERT Embedding Shape for the word 'healthcare':", bert_embedding.shape)

BERT Embedding Shape for the word 'healthcare': torch.Size([1, 768])


### Sentence Embeddings:

### Sentence BERT

In [ ]:
sentences = paragraphs
for i in sentences:
  if i == '':
    sentences.remove(i)

len(sentences)

10

In [ ]:
# Define a function to obtain BERT embeddings for a sentence
def get_bert_embedding(sentence):
    inputs = tokenizer(sentence, return_tensors="pt")
    outputs = model(**inputs)
    embeddings = outputs.last_hidden_state.mean(dim=1)  # Taking the mean of hidden states as the sentence embedding
    return embeddings

In [ ]:
# Example usage
sentence = sentences[0]
bert_embedding = get_bert_embedding(sentence)

print("BERT Embedding Shape:", bert_embedding.shape)

BERT Embedding Shape: torch.Size([1, 768])


### Doc to Vec

In [ ]:
from gensim.models.doc2vec import Doc2Vec,TaggedDocument

In [ ]:
from nltk.tokenize import word_tokenize

# preproces the documents, and create TaggedDocuments
tagged_data = [TaggedDocument(words=word_tokenize(doc.lower()),tags=[str(i)]) for i,
               doc in enumerate(sentences)]

In [ ]:
# train the Doc2vec model
model = Doc2Vec(vector_size=20,min_count=2, epochs=50)
model.build_vocab(tagged_data)
model.train(tagged_data,total_examples=model.corpus_count,epochs=model.epochs)

# get the document vectors
document_vectors = [model.infer_vector(word_tokenize(doc.lower())) for doc in sentences]

#  print the document vectors
for i, doc in enumerate(sentences):
    print("Document", i+1, ":", doc)
    print("Vector:", document_vectors[i])
    print()

Document 1 : Cardiovascular health is crucial for overall well-being. Regular exercise, a balanced diet, and avoiding smoking are key factors in maintaining a healthy heart. It's essential to monitor cholesterol levels and blood pressure regularly.
Vector: [-0.00477222  0.42599997  0.54016453 -0.03543132 -0.25433007 -0.51516134
 -0.28033397  0.91300035 -1.1725427  -0.61782813  0.45568112  0.60540575
 -0.44678783 -0.69293797  0.20561256  0.2875479   1.1921942  -0.23941943
 -1.167258   -0.79966646]

Document 2 : Diabetes is a chronic condition that requires careful management. Individuals with diabetes should focus on controlling their blood sugar levels through a combination of diet, exercise, and medication as prescribed by their healthcare provider.
Vector: [-0.01078541  0.26738492  0.3756035  -0.0065476  -0.18831104 -0.34951898
 -0.20996797  0.6358318  -0.84370136 -0.4344047   0.3450166   0.42073938
 -0.27781358 -0.47146264  0.15560281  0.20703818  0.83932585 -0.1362186
 -0.82698196 

### Universal Sentence Encoder

In [ ]:
# import necessary libraries
import tensorflow_hub as hub

# Load pre-trained universal sentence encoder model
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [ ]:
embeddings = embed(sentences)

# Printing embeddings of each sentence
print(embeddings)

# To print each embeddings along with its corresponding
# sentence below code can be used.
for i in range(len(sentences)):
    print(sentences[i])
    print(embeddings[i])

tf.Tensor(
[[-0.04377037 -0.05734012 -0.02139249 ...  0.07113744 -0.05311307
  -0.00031633]
 [-0.03396959 -0.02956964  0.01318436 ...  0.07416128 -0.01614095
  -0.05093965]
 [-0.01069618 -0.01775396  0.06702132 ...  0.06956717 -0.06637956
  -0.05749491]
 ...
 [-0.01988761 -0.02413709 -0.06241564 ...  0.07612298 -0.02335496
   0.01662752]
 [-0.0385791  -0.03823084  0.03331903 ...  0.07388219 -0.00692947
  -0.04203615]
 [-0.0589052  -0.00314605  0.05445509 ...  0.08169486 -0.0515089
   0.0638934 ]], shape=(10, 512), dtype=float32)
Cardiovascular health is crucial for overall well-being. Regular exercise, a balanced diet, and avoiding smoking are key factors in maintaining a healthy heart. It's essential to monitor cholesterol levels and blood pressure regularly.
tf.Tensor(
[-4.37703691e-02 -5.73401190e-02 -2.13924926e-02  6.41302317e-02
  5.66981696e-02 -6.81604892e-02  3.53182554e-02 -1.42158186e-02
  3.47138308e-02  4.46442962e-02  7.01209232e-02 -3.75377610e-02
 -5.23234233e-02 -6.381

### Chatbot Skeleton

In [ ]:
# Define Greeting functions:
import random

greet_inputs = ("Hello!","Hi there")
greet_responses = ("Hey there!", "Hi!", "Hello.")
def greet(sentence):
  for word in sentence.split():
    if word.lower() in greet_inputs:
      return random.choice(greet_responses)

### Chatbot using TFIDF and Cosine Similarity

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def response(user_response):
  robo1_response = ""
  TfidfVec = TfidfVectorizer(tokenizer = tokenize_and_lemmatize, stop_words = "english")
  tfidf = TfidfVec.fit_transform(sentences)

  vals = cosine_similarity(tfidf[-1], tfidf)
  idx = vals.argsort()[0][-2]
  flat = vals.flatten()
  flat.sort()

  req_tfidf = flat[-2]
  if req_tfidf == 0:
    robo1_response += "Sorry, I can't understand you."
    return robo1_response
  else:
    robo1_response += sentences[idx]
    return robo1_response


In [ ]:
# Defining the chatflow
flag = True
print("Greetings! I am a healthcare chatbot. Feel free to ask your health related queries. Type Bye for ending conversation")
while flag == True:
  user_response = input()
  user_response = user_response.lower()

  if user_response != 'bye':
    if (user_response == "thank you" or user_response == "thanks"):
      flag = False
      print("Bot: You are welcome!")
    else:
      if(greet(user_response) != None):
        print("Bot:"+greet(user_response))
      else:
        temp = []
        sentences.append(user_response)
        temp.append(nltk.word_tokenize(user_response))
        para.extend(temp)
        final_words = list (set(para[0]))

        print("Bot: ", end="")
        print(response(user_response))

        sentences.remove(user_response)
  else:
    flag = False
    print("Bot: Goodbye!")

Greetings! I am a healthcare chatbot. Feel free to ask your health related queries. Type Bye for ending conversation
what is healthcare?
Bot: Prevention is key in healthcare. Regular check-ups with healthcare providers, vaccinations, and screenings for common health conditions contribute to early detection and effective management.
why is sleep important?
Bot: Adequate sleep is crucial for cognitive function and overall health. Establishing a consistent sleep routine, creating a comfortable sleep environment, and avoiding stimulants before bedtime can contribute to better sleep quality.
what is diabetes?
Bot: Diabetes is a chronic condition that requires careful management. Individuals with diabetes should focus on controlling their blood sugar levels through a combination of diet, exercise, and medication as prescribed by their healthcare provider.
What is a balanced diet?
Bot: Cardiovascular health is crucial for overall well-being. Regular exercise, a balanced diet, and avoiding smo

In [ ]:
for i in para:
  print(i)

['cardiovascular', 'health', 'crucial', 'overall', 'wellbee', 'regular', 'exercise', 'balanced', 'diet', 'avoid', 'smoking', 'key', 'factor', 'maintain', 'healthy', 'heart', 'essential', 'monitor', 'cholesterol', 'level', 'blood', 'pressure', 'regularly']
['diabetes', 'chronic', 'condition', 'require', 'careful', 'management', 'individual', 'diabete', 'focus', 'control', 'blood', 'sugar', 'level', 'combination', 'diet', 'exercise', 'medication', 'prescribe', 'healthcare', 'provider']
['mental', 'health', 'important', 'physical', 'health', 'stress', 'management', 'technique', 'meditation', 'deep', 'breathing', 'exercise', 'contribute', 'overall', 'wellbeing', 'experience', 'persistent', 'mental', 'health', 'issue', 'seek', 'professional', 'help', 'advisable']
['adequate', 'sleep', 'crucial', 'cognitive', 'function', 'overall', 'health', 'establish', 'consistent', 'sleep', 'routine', 'create', 'comfortable', 'sleep', 'environment', 'avoid', 'stimulant', 'bedtime', 'contribute', 'well', '